### PR TITLE
Merge pull request #1 from lucent-sea/master

### PR DESCRIPTION
**Pull request by Fimeg**

### CODE REVIEW

**Comment by lucent-sea** [comment]
Hey there.

It looks like you might be trying to start a build, maybe?

I'm really close to having this ready, but it's not quite ready yet.  I'd recommend holding off until I have some tooling completed that I'm working on.  :) 

I'll post an update in the below discussion thread when it's ready:

https://github.com/lucent-sea/Remotely/discussions/257

**Comment by Fimeg** [comment]
Apologies; I do seem to be caught in my own circles... The option "switching the base" is completely undiscoverable by me, and it seems I've 3 times requested a pull request into your repo instead of my own. :)

**Comment by lucent-sea** [comment]
I plan on doing a full instructional video later.

This should be how you it looks on your end, though: Imgur: The magic of the Internet<https://imgur.com/a/b9dm8W9>

Let me know if that helps.  😊

**Comment by lucent-sea** [comment]
Hmm.  It looks like I might be able to get the build to pull from my repo instead, so the fork doesn’t need to be updated.  I’ll look into it later in the week if I have time.  😊

**Pull request closed without merging**
