### PR TITLE
Address Ubuntu Error with Agent

### PR DESCRIPTION
**Pull request by RecursiveProgrammer**
---

Please read the following.  Do not delete below this line.

---

Thank you for your contribution to the Remotely project.  It is required that contributors assign copyright to me (Jared Goodwin) so that I retain full ownership of the project.

This makes it easier for other entities to use the software because they only have to deal with one copyright holder.  It also gives me assurance that I'll be able to make decisions in the future without gathering and consulting all contributors.

While this may seem odd, many open source maintainers practice this.  Here are a couple well-known examples:

- Free Software Foundation: http://www.gnu.org/licenses/why-assign.html
- Microsoft: https://cla.opensource.microsoft.com/

A nice article on the topic can be found here:  https://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/

By submitting this PR, you agree to the following:

> You hereby assign copyright in this PR's code to the Remotely project and its copyright holder, Jared Goodwin, to be licensed under the same terms as the rest of the code.  You agree to relinquish any and all copyright interest in the software, to the detriment of your heirs and successors.

---

Minor updates: Added a makefile to help me compile the Agent: you can ignore this file if you prefer. I also was receiving an error with '& disown'. This may be specific to Ubuntu, though. I am not sure how I would create a Unit test to show the error while connecting to the client machine. I will keep an eye out for tutorials on what needs to be done to create unit tests.

### CODE REVIEW

**Comment by lucent-sea** [comment]
The arguments aren't throwing.  They're just being logged as unrecognized parameters, because I added them after the command line parsing stuff and haven't updated it to ignore them.  That's why they're written as `Info` level.

```
2021-03-09 07:36:31.832 [Info] Command line arguments are invalid.  Key: &
2021-03-09 07:36:31.832 [Info] Command line arguments are invalid.  Key: disown
```

Without `disown`, the new process (e.g. the desktop app that captures the screen) would exit as soon as the thread that spawned it is terminated.  I don't know if that's changed in .NET 5, but I wouldn't remove it for the sake of removing a couple log entries.

**Comment by lucent-sea** [comment]
I tested this briefly, and it seems to be working.

Could you please test chat and unattended remote control on Ubuntu and Manjaro, and let me know that it's all working?

Thanks.  :)

**Comment by RecursiveProgrammer** [comment]
Using manjaro and XFCE: Appears to be working. Disconnected and reconnected without the agent losing connection. Chat seems to be working on both. I did see an error on Manjaro involving binding to Avalonia.Controls.Button.CommandParameter: Null value in expression ''.' . I think this message is appearing in the current build, as well. I shall look into what is causing this message, next.

**Comment by lucent-sea** [comment]
Awesome.  Much appreciated.

Yeah, that XAML binding error was pre-existing.  If you want to look into it, that'd be cool, but it doesn't affect this PR.

I'll merge this in when I get off work.

Thanks!

**Review by lucent-sea — APPROVED** [review]

**Pull request merged**
